# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title_en', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title_cn', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('content_md', models.TextField()),
                ('content_html', models.TextField()),
                ('content_text', models.TextField()),
                ('tags', models.CharField(help_text='务必用英文逗号分割', max_length=50, verbose_name='标签组')),
                ('view_times', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('comment_times', models.IntegerField(default=0)),
                ('auther', models.CharField(default='高亮', max_length=100)),
            ],
            options={
                'ordering': ['create_time'],
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('floor', models.IntegerField()),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
